# 🔴 Dictionary of fake news keywords with assigned weights
# These keywords are commonly found in misleading or exaggerated headlines
# Higher weight = stronger fake indication
fake_keywords = {
    "shocking": 2,
    "click here": 3,
    "miracle cure": 2,
    "you won't believe": 3,
    "jaw-dropping": 2,
    "hidden truth": 2,
    "they don't want you to know": 3,
    "exposed": 2,
    "secret revealed": 2,
    "viral secret": 1,
    "banned": 2,
    "wake up": 2,
    "this changes everything": 3,
    "leaked": 2,
    "exclusive footage": 2,
    "sensational claim": 2,
    "urgent warning": 2,
    "what happened next": 3,
    "medical breakthrough": 2,
    "cure all": 2,
    "doctors hate": 2,
    "media won't show": 2,
    "agenda exposed": 2,
    "once in a lifetime": 2,
    "mind-blowing": 2,
    "hidden agenda": 2,
    "truth revealed": 2,
    "conspiracy exposed": 2,
    "this will change your life": 3,
    "don’t tell you": 3,
    "warning shocking": 3,
    "exclusive leak": 2,
    "unbelievable evidence": 2,
    "secret they don’t want revealed": 3,
    "urgent": 2,
    "alert": 2,
    "epic reveal": 2,
    "viral claim": 1,
    "astonishing": 2,
    "incredible": 2,
     "breaking": 2,
}


# ✅ Dictionary of real news keywords with assigned weights
# These terms are usually found in reliable and factual headlines
# Higher weight = stronger real news indication
real_keywords = {
    "official statement": 2,
    "peer-reviewed study": 2,
    "research findings": 2,
    "government report": 2,
    "verified sources": 2,
    "public health data": 2,
    "expert analysis": 2,
    "confirmed by": 2,
    "evidence shows": 2,
    "analysis of": 1,
    "investigation": 2,
    "update": 1,
    "announced": 1,
    "study": 2,
    "data": 2,
    "trusted agency": 2,
    "source confirmed": 2,
    "press release": 1,
    "scientific consensus": 2,
    "tested": 2,
    "reviewed": 2,
    "verifiable": 2,
    "official report": 2,
    "verified by": 2,
    "survey results": 2,
    "academic sources": 2,
    "published": 1,
    "documents confirm": 2,
    "regulatory approved": 2,
    "experts agree": 2,
    "fact-checked": 2,
    "confirmed by researchers": 2,
    "field study": 2,
    "press conference": 1,
    "transparent": 1,
    "journal article": 2,
    "evidence-based": 2,
    "signed official": 2
}
